// <auto-generated />
namespace KongOrange.Squares.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SquareSetPieceNameRemoved : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SquareSetPieceNameRemoved));
        
        string IMigrationMetadata.Id
        {
            get { return "201605161149543_SquareSetPieceNameRemoved"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
